{% set name = "starship" %}
{% set version = "1.20.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 851d84be69f9171f10890e3b58b8c5ec6057dd873dc83bfe0bdf965f9844b5dc

build:
  number: 1
  ignore_run_exports_from:
    # we want to ignore libstdcxx, but not libgcc; the latter also comes in through
    # compiler('c'), and conda keeps that despite ignoring the cxx run-exports
    - {{ compiler('cxx') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - make  # [linux]
    - cmake  # [not win]
    - cargo-bundle-licenses
  run:

test:
  commands:
    - starship -h

about:
  home: https://starship.rs/
  license: ISC
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: The minimal, blazing-fast, and infinitely customizable prompt for any shell!
  dev_url: https://github.com/starship/starship

extra:
  recipe-maintainers:
    - m-rossi
