{% set name = "starship" %}
{% set version = "1.24.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4f2ac4181c3dea66f84bf8c97a3cb39dd218c27c8e4ade4de149d3834a87c428

build:
  number: 0
  ignore_run_exports_from:
    # we want to ignore libstdcxx, but not libgcc; the latter also comes in through
    # compiler('c'), and conda keeps that despite ignoring the cxx run-exports
    - {{ compiler('cxx') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - make  # [not win]
    - cmake  # [not win]
    - cargo-bundle-licenses
  run:

test:
  commands:
    - starship -h

about:
  home: https://starship.rs/
  license: ISC
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: The minimal, blazing-fast, and infinitely customizable prompt for any shell!
  dev_url: https://github.com/starship/starship

extra:
  recipe-maintainers:
    - m-rossi
