{% set name = "starship" %}
{% set version = "1.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2f068545f270733add06c90592f3fb36422b8f650853f707956d24c06041b751

build:
  number: 0
  ignore_run_exports_from:
    # we want to ignore libstdcxx, but not libgcc; the latter also comes in through
    # compiler('c'), and conda keeps that despite ignoring the cxx run-exports
    - {{ compiler('cxx') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - make  # [linux]
    - cmake  # [not win]
    - cargo-bundle-licenses
  run:

test:
  commands:
    - starship -h

about:
  home: https://starship.rs/
  license: ISC
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: The minimal, blazing-fast, and infinitely customizable prompt for any shell!
  dev_url: https://github.com/starship/starship

extra:
  recipe-maintainers:
    - m-rossi
